# This workflow will lint, run tests, and type check with Python 3.11

name: Build and test app

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov mypy
        pip install -r requirements.txt

    - name: Lint with Ruff
      run: ruff check --output-format=github

    - name: Check code formatting with Ruff
      run: ruff format --diff
      continue-on-error: true

    - name: Run tests and report coverage
      run: |
        pytest --cov-report term-missing --cov=myproj tests/

    - name: Run type checking with mypy
      run: mypy ../../ --check-untyped-defs --disable-error-code=import-untyped
