name: Deploy app to AWS Lambda

on:
  push:
    branches:
      - main
      - dev
      - staging
  repository_dispatch:
    types: [deploy-staging]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set branch name
        id: set-branch
        run: |
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            echo "BRANCH=${{ github.event.client_payload.branch }}" >> $GITHUB_ENV
          else
            echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi

      - name: Create directory structure
        run: mkdir -p package

      - name: Copy application files
        run: |
          rsync -av --exclude='package' --exclude='.git' ./ package/

      - name: Install zip command
        uses: montudor/action-zip@v1

      - name: Create zip file for Lambda function
        run: |
          cd package
          zip -r ../code.zip .

      - name: Install AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest

      - name: Deploy Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name traffic_data_function \
            --zip-file fileb://code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Create Lambda Layer
        run: |
          mkdir -p python/lib/python3.12/site-packages
          pip install -r src/requirements.txt -t python/lib/python3.12/site-packages
          zip -r lambda-layer.zip python

      - name: Deploy Lambda Layer and attach to function
        run: |
          LAYER_VERSION=$(aws lambda publish-layer-version \
            --layer-name my-dependencies-layer \
            --description "Dependencies for Flask API" \
            --zip-file fileb://lambda-layer.zip \
            --compatible-runtimes python3.12 \
            --output text --query 'LayerVersionArn')

          aws lambda update-function-configuration \
            --function-name traffic_data_function \
            --layers $LAYER_VERSION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Wait for function update to complete
        run: |
          aws lambda wait function-updated \
            --function-name traffic_data_function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Publish new Lambda version
        id: publish
        run: |
          VERSION=$(aws lambda publish-version \
            --function-name traffic_data_function \
            --output text --query 'Version')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Create or update Lambda alias
        run: |
          ALIAS_NAME=$([[ "${BRANCH}" == "main" ]] && echo "prod" || ([[ "${BRANCH}" == "staging" ]] && echo "staging" || echo "dev"))
          echo "Setting alias to $ALIAS_NAME -> version $VERSION"

          if aws lambda get-alias --function-name traffic_data_function --name $ALIAS_NAME > /dev/null 2>&1; then
            aws lambda update-alias \
              --function-name traffic_data_function \
              --name $ALIAS_NAME \
              --function-version $VERSION
          else
            aws lambda create-alias \
              --function-name traffic_data_function \
              --name $ALIAS_NAME \
              --function-version $VERSION
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          VERSION: ${{ env.VERSION }}
          BRANCH: ${{ env.BRANCH }}