name: Deploy app to AWS Lambda

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create directory structure
        run: |
          mkdir -p package  # Create a separate folder for dependencies

      - name: Copy application files to the root of the package
        run: |
          cp -r $(ls | grep -v 'package' | grep -v '.git') package/  # Copy application files to package root

      - name: Install zip command
        uses: montudor/action-zip@v1

      - name: Create zip file for Lambda function
        run: |
          cd package
          zip -r ../code.zip .
  
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:428842100366:function:traffic_data_function \
            --zip-file fileb://code.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
      
      - name: Create Lambda Layer
        run: |
          mkdir -p python/lib/python3.12/site-packages
          pip install -r requirements.txt -t python/lib/python3.12/site-packages
          zip -r lambda-layer.zip python
          cd ..
        
      - name: Deploy Lambda Layer and attach to function
        run: |
          LAYER_VERSION=$(aws lambda publish-layer-version \
            --layer-name my-dependencies-layer \
            --description "Dependencies for Flask API" \
            --zip-file fileb://lambda-layer.zip \
            --compatible-runtimes python3.12 \
            --output text --query 'LayerVersionArn')
          
          # Update Lambda function to use this layer
          aws lambda update-function-configuration \
            --function-name traffic_data_function \
            --layers $LAYER_VERSION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Wait for function update to complete
        run: |
          aws lambda wait function-updated \
            --function-name traffic_data_function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Publish Lambda version
        id: publish
        run: |
          VERSION=$(aws lambda publish-version \
            --function-name traffic_data_function \
            --output text --query 'Version')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Create or update Lambda alias
        run: |
          ALIAS_NAME=$([[ "${GITHUB_REF##*/}" == "main" ]] && echo "prod" || echo "dev")
          echo "Setting alias to $ALIAS_NAME -> version $VERSION"

          if aws lambda get-alias --function-name traffic_data_function --name $ALIAS_NAME > /dev/null 2>&1; then
            aws lambda update-alias \
              --function-name traffic_data_function \
              --name $ALIAS_NAME \
              --function-version $VERSION
          else
            aws lambda create-alias \
              --function-name traffic_data_function \
              --name $ALIAS_NAME \
              --function-version $VERSION
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          VERSION: ${{ env.VERSION }}
